### ISSUE TITLE
Add Existing WMS

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/NeatlineMaps#11]
System needs to be able to add an already existing map from a Geoserver instance. Example workflow:
- Upload map
- Change mind on item
- Delete Item
- Create new item
- Associate item with map

Another use case is where a scholar doesn't have write permission to the geoserver instance, but the resource is there:
- Someone with a geoserver access uploads a map
- You create an Omeka item
- Associate a map with an item

**Comment by davidmcclure** [comment]
Fixed (provisionally, at least) by Neatline WMS.
