### ISSUE TITLE
Multiple files of close-ish file names

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/NeatlineMaps#12]
If you have a geotiff that you upload (e.g. hotchkiss.tif) at one resolution, then upload another with a similarly file with a different file extention (hotchkiss.tiff), Geoserver will produce an error on creating the coverage store as it already exists. This produces an error in the maps admin interface.

**Comment by erochest** [comment]
Neither @davidmcclure or I can reproduce this.

At the moment, either uploading a new file with the same name or with a different extension (`.tif` and `.tiff`) clobbers the store with the new data.
