### ISSUE TITLE
Uninstalling should wipe NeatlineMaps data

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/NeatlineMaps#28]
Except in rare cases, uninstalling plugins that have added data to Omeka also deletes any data added through the plugin. I would suggest NeatlineMaps do the same, unless we have specific reasons not to. This would involve removing the tables for Neatline Maps servers and maps themselves.

The scope of this should be discussed further.

**Comment by davidmcclure** [comment]
Done.
