### ISSUE TITLE
add_mime_display_type() breaks the plugin in Omeka 2.0

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/NeatlineMaps#37]
The call to add_mime_display_type() in NeatlineMapsPlugin->addHooksAndFilters() shuts down the entire plugin in 2.0 (discovered while installing a fresh version of the plugins on Webfaction).

**Comment by jeremyboggs** [comment]
We'll likely need to add version checks for Omeka 1.5 and 2.0 in various parts of the plugin, since there are some significant changes in Omeka 2.0.

**Comment by erochest** [comment]
We should start a feature branch for 2.0 compatibility.

One option would be to include an singleton adapter class that handles all the code checks and everything. All calls to Omeka code that would hit an incompatible API call would be routed through this class. We could share that amongst all the plugins (git submodule?).

Let's see. Have I left out any GoF patterns? A flywheel. It needs to use a flywheel.

**Comment by jeremyboggs** [comment]
> Let's see. Have I left out any GoF patterns? A flywheel. It needs to use a flywheel.

I'm personally embarrassed we shipped this without a flywheel.

**Comment by jeremyboggs** [comment]
@davidmcclure Could you provide some more details for this ticket? Any error messages? I just tried commenting out the call to `add_mime_display_type` and the plugin still doesn't work, so am wondering if there's something else going on.

**Comment by jeremyboggs** [comment]
Recommend closing this, since 1) `add_mime_display_type` still exists in 2.0, and 2) there are broader incompatibilities between our plugins and Omeka 2.0.
