### ISSUE TITLE
Remove check for Historical map type, rely on data from file

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/NeatlineMaps#4]
To make a map in NeatlineMaps, you have to select the item type "Historical map", then upload a GeoTIFF. Instead, we could remove the check for the item type, and instead read the GeoTIFF file's metadata to display it in the NeatlineMaps wrapper.

The advantage in doing this is users could upload a GeoTIFF to any item, regardless of type, and have the map render correctly.

**Comment by waynegraham** [comment]
Stale ticket...
